vich_uploader:
  db_driver: orm

  mappings:
    product_image:
      uri_prefix: /products/images
      upload_destination: '%kernel.project_dir%/public/products/images'
      namer: Vich\UploaderBundle\Naming\UniqidNamer
    event_image:
      uri_prefix: /events/images
      upload_destination: '%kernel.project_dir%/public/events/images'
      namer: Vich\UploaderBundle\Naming\UniqidNamer
